DZ-1
Pavel4en/2024-2-VK-EDU-Frontend-P-Chen pull request #1
Opened 2024-09-29 05:51 UTC by Pavel4en

# Домашнее задание No 1
Прошу @martinkomitsky, @haseprogram, @kgrechin или @Ivan-Bir проверить его.

2024-09-29 10:30 UTC, Ivan-Bir requested changes

2024-09-29 10:30 UTC, Ivan-Bir commented on .gitignore
> +node_modules/
Привет! Добро пожаловать на курс
Я буду твоим ментором и буду рад ответить на любые вопросы по курсу

2024-09-29 10:30 UTC, Ivan-Bir commented on .gitignore
> +node_modules/
Не забываем добавлять пустую строку в конец файла. Это поможет в будущем избегать ошибок мержа

2024-09-29 10:30 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  if (typeof bytes !== 'number' || bytes < 0) {
Посмотри что будет, если передать NaN. Покрыть тестом

2024-09-29 10:30 UTC, Ivan-Bir commented on correctSentence.js
> +  if (!text) return text;
Даже для однострочных ифаков принято использовать {}

2024-09-29 10:30 UTC, Ivan-Bir commented on correctSentence.js
> +  const capitalizedText = text.charAt(0).toUpperCase() + text.slice(1);
Лучше использовать шаблонные строки ${var1} ${var2}, это безопаснее с точки зрения возможных неявных преобразований. Здесь и далее

2024-09-29 10:30 UTC, Ivan-Bir commented on nonUniqueElements.js
> +  return data.filter(item => elementCount[item] > 1);
Даже если у стрелочной функции один параметр, то его принято оборачивать в скобки

2024-09-29 10:30 UTC, Ivan-Bir commented on nonUniqueElements.test.js
> +  expect(nonUniqueElements([10, 9, 10, 10, 9, 8])).toEqual([10, 9, 10, 10, 9]);
Нет тестов на граничные случаи

2024-09-29 10:30 UTC, Ivan-Bir commented on correctSentence.test.js
> +  expect(correctSentence("greetings, friends")).toBe("Greetings, friends.")
Нет тестов на граничные случаи

2024-09-29 10:30 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для неправильного типа данных', () => {
Обычно все данные хранятся в целых байтах. Если на входе float, то в функции смотреть только на целую часть. Добавить на это тест соответственно.

2024-09-30 08:49 UTC, Ivan-Bir approved these changes
Есть незначительные замечания. Можно поправить. Апрув ставлю

2024-09-30 08:49 UTC, Ivan-Bir commented on convertBytesToHuman.js
> +  const integerBytes = Math.floor(bytes);
Эта переменная дальше нигде не используется. Почему бы её сразу не использовать в цикле?

2024-09-30 08:49 UTC, Ivan-Bir commented on convertBytesToHuman.test.js
> +test('Возвращает false для NaN', () => {
Это не отдельная группа, а просто неверный тип данных

2024-09-30 08:49 UTC, Ivan-Bir commented on correctSentence.test.js
> +});
Забылась строка в конце файла

2024-09-30 19:39 UTC, martinkomitsky approved these changes
12!

2024-09-30 19:40 UTC, merged